---
- name: Converge
  hosts: all
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: docker-graylog
  # tasks:
  # - name:
  #   - log something
  vars:
    docker_package: "docker-{{ docker_edition }}"
    docker_package_version: "17.03.2.ce-1.el7.centos"
    docker_hosts:
      - "unix:///var/run/docker.sock"
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_graylog_enable_web_host_port: true
    docker_graylog_enable_gelf_udp_host_port: true
